- precommit/src/main/shell/personality/hadoop.sh
Ozone/Hdds projects are not handled very well in the hadoop personality as in case of an ozone change all the hdds/ozone projects should be built and tested
> YETUS-816. Improve hadoop personality to support ozone/hdds projects

- .circleci/config.yml
- .gitlab-ci.yml
- Jenkinsfile
- precommit/src/main/shell/test-patch.d/junit.sh
This is a very simple implementation that likely requires more work.  But it does work for at least Circle CI and Gitlab to some degree.
> YETUS-685. add junit xml as a reporting format

- precommit/src/main/shell/core.d/builtin-bugsystem.sh
The final output table is a wall of text. If you squint a little, you
can see that there are subsections contained within. Add some visual
separation between sections so that one can navigate the results.
Before this change:
```
| Vote |       Subsystem |  Runtime   | Comment
============================================================================
|      |                 |            | Prechecks
|  +1  |        dupname  |   0m  0s   | No case conflicting files found.
|  +1  |      hbaseanti  |   0m  0s   | Patch does not have any anti-patterns.
|  +1  |        @author  |   0m  0s   | The patch does not contain any @author
|      |                 |            | tags.
|  +1  |     test4tests  |   0m  0s   | The patch appears to include 4 new or
|      |                 |            | …
```
> YETUS-926. Add visual separation to console report summary

- .github/workflows/yetus.yml
- asf-site-src/source/documentation/in-progress/precommit-basic.html.md
- asf-site-src/source/documentation/in-progress/precommit-robots.html.md
- precommit/src/main/shell/core.d/00-yetuslib.sh
- precommit/src/main/shell/core.d/docker.sh
- precommit/src/main/shell/robots.d/githubactions.sh
- precommit/src/main/shell/test-patch.d/github.sh
- precommit/src/main/shell/test-patch.sh
While working on this, I also hit:
* YETUS-844: docker check breaks on moby-cli
* YETUS-940: semaphore CI or GHSHA broken? (answer: semaphore CI, but really neither, because PATCH_OR_ISSUE was getting wiped and BUILDMODE set to full was getting dropped when switching to Docker!  This is partially fixed, but not completely.)
* --docker-work-dir didn't actually work
* tput errors were being displayed
* --dockertag was in the message when the option is actually --docker-tag
> YETUS-947. Support github actions as a robot

- precommit/src/main/shell/personality/hadoop.sh
JIRA: https://issues.apache.org/jira/browse/YETUS-895
> YETUS-895. Add ZStandard Compression support in Hadoop personality

- precommit/src/main/shell/test-patch-docker/Dockerfile
JIRA: https://issues.apache.org/jira/browse/YETUS-960
> YETUS-960. Yetus build env cannot execute pylint2

- precommit/src/main/shell/test-patch.d/maven.sh
JIRA: https://issues.apache.org/jira/browse/YETUS-972
> YETUS-972. Make javadoc phase and goal configurable in maven.sh

- asf-site-src/source/documentation/in-progress/precommit/bugsystems.html.md
- asf-site-src/source/documentation/in-progress/precommit/plugins/github.html.md
- asf-site-src/source/documentation/in-progress/precommit/robots/jenkins.html.md
- precommit/src/main/shell/robots.d/jenkins.sh
- precommit/src/main/shell/test-patch.d/github.sh
- precommit/src/main/shell/test-patch.d/junit.sh
* includes some docs updates to reflect
what is supported for github
> YETUS-1022. Get commit sha from github PR json

- precommit/src/main/shell/robots.d/githubactions.sh
- precommit/src/main/shell/test-patch.d/asflicense.sh
- precommit/src/main/shell/test-patch.d/author.sh
- precommit/src/main/shell/test-patch.d/checkstyle.sh
- precommit/src/main/shell/test-patch.d/dupname.sh
- precommit/src/main/shell/test-patch.d/maven.sh
- precommit/src/main/shell/test-patch.d/pathlen.sh
- precommit/src/main/shell/test-patch.d/unitveto.sh
- precommit/src/main/shell/test-patch.sh
* Added group control to github actions output to make it
easier to debug
* Changed the remaining diff- to results-
* Reformatted asflicense output, now calls b_l_queue
* Reformatted author output (where possible), now calls b_l_queue
* Reformatted dupname output, now calls b_l_queue
* Reformatted maven javac output, now uses column_calcdiffs
* Reformatted maven javadoc output, now users error_calcdiffs
* Reformatted pathlen output, now calls b_l_queue
* Reformatted unitveto output, now cals b_l_queue
* b_l_queue rejects plug-ins that are in the tests filter
* b_l_queue verifies that the first column exists
* modules_messages now calls b_l_queue
There are likely other plug-ins that will need massaging
(esp ant and gradle), but this covers a good chunk of missing
functionality for the most …
> YETUS-1028. Various missing github annotations

- shelldocs/src/main/python/shelldocs.py
JIRA: https://issues.apache.org/jira/browse/YETUS-1099
> YETUS-1099. shelldocs --lint option fails

- precommit/src/main/shell/plugins.d/github.sh
JIRA: https://issues.apache.org/jira/browse/YETUS-1102
- Add `--github-write-comment` to back to the previous behavior.
- Add back `--github-use-emoji-vote` option.
> YETUS-1102. Add an option to comment to GitHub PR.

- precommit/src/main/shell/plugins.d/test4tests.sh
* The regex used to detect test changes
only caters to the case where there's
a directory named "test".
* Conventionally, the tests in CMake are
put under a directory named "tests".
This causes the regex match to fail and
thus results in a -1 for test4tests.
* We handle this case by matching "test"
with an optional trailing "s".
> YETUS-1106. Detect CMake test changes

- asf-site-src/source/documentation/in-progress/precommit/plugins/blanks.html.md
The documentation incorrectly listed `.yetus/blanks-eol.txt` as the default ignore file for the blank-tabs-test. It should be `.yetus/blanks-tabs.txt`. 
This PR fixes that.
> Fixes YETUS-1116. Documentation for blank-test incorrect

- audience-annotations-component/audience-annotations/src/main/java/org/apache/yetus/audience/tools/DocletEnvironmentProcessor.java
- audience-annotations-component/audience-annotations/src/main/java/org/apache/yetus/audience/tools/ExcludePrivateAnnotationsStandardDoclet.java
- audience-annotations-component/audience-annotations/src/test/java/org/apache/yetus/audience/tools/DocletEnvironmentProcessorTest.java
- pom.xml
Fixes the first problem that was caused because the yetus options weren't comparable to the standard option objects. I changed the TreeSet to a HashSet, which does not require more than hashCode & equals.
> YETUS-1155: Fix site:site treeset problem

- .cirrus.yml
- .github/workflows/action-test.yml
- .github/workflows/ghcr.yml
- .github/workflows/linkcheck.yml
- .github/workflows/yetus.yml
- .gitlab-ci.yml
- .travis.yml
- asf-site-src/source/documentation/in-progress/precommit/robots/githubactions.html.md
- precommit/src/main/shell/core.d/00-yetuslib.sh
- precommit/src/main/shell/core.d/01-common.sh
- precommit/src/main/shell/robots.d/cirrusci.sh
- precommit/src/main/shell/robots.d/travisci.sh
- precommit/src/main/shell/smart-apply-patch.sh
- precommit/src/main/shell/test-patch.sh
- release/initial-patches.sh
This patch does a few things:
* updates various github actions to the latest versions which help fix things on the Github-side
* Adds a new yetus_is_container feature routine which helps us figure out if code is running in a container
* Moves the BASEDIR/.git check to be in routine in common
* If precommit is running in a container, set GIT_DIR and GIT_CEILING_DIRECTORIES which will prevent git from going past our source tree.  We do not set these outside of the container because there is an assumption the user knows what they are doing.
* Associated documentation
NOTE: this code will almost certainly still fail the Action Test GHA until it is committed to main.
> YETUS-1159. fixes for CVE-2022-24765

- .gitignore
- .mvn/maven.config
- .yetus/excludes.txt
- asf-site-src/pom.xml
- audience-annotations-component/audience-annotations/pom.xml
- audience-annotations-component/pom.xml
- pom.xml
- precommit/pom.xml
- precommit/src/main/shell/core.d/01-common.sh
- precommit/src/main/shell/test-patch.sh
- release/initial-patches.sh
- releasedocmaker/pom.xml
- shelldocs/pom.xml
- yetus-assemblies/pom.xml
- yetus-dist/pom.xml
- yetus-maven-plugin/pom.xml
Also fixing various issues that prevent test-patch --version from working correctly.  Woops.
> YETUS-1161. Switch pom versions to use maven.config

- asf-site-src/source/documentation/in-progress/precommit/index.html.md
Forgot to link the docs from the main index. woops.
> YETUS-1166. Add jsonlint support (addendum)

- precommit/src/main/shell/plugins.d/golangci.sh
In order to have all complains in results of golangci we should set
uniq-by-line to false. Having uniq-by-line equals true (default) force
golangci to output only the first error per line comes from linters in
random order. Random errors give us unpredictable diff between branch
and patch results.
Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>
> YETUS-1191. Add uniq-by-line option to golangci

- asf-site-src/Gemfile
- asf-site-src/Gemfile.lock
- precommit/src/main/shell/test-patch-docker/Dockerfile
- Hard-set haml to 5.2.2 since 6.x blows up our build
- Upgrade bundler to latest
- Run bundler upgrade to update everything else
manual inspection of mvn site output looked idential
> YETUS-1201. update ruby components to deal with CVEs

- asf-site-src/source/contribute/releases.html.md
- release/initial-patches.sh
The remaining parts of the docs update from 0.14.0 that enables main to have version tags in it.
> YETUS-1181. post-0.14.0 release doc updates (pt2)
