README.md

https://issues.apache.org/jira/browse/YETUS-925

YETUS-925. Fix link error in README.md

---

precommit/src/main/shell/test-patch.d/checkstyle.sh

JIRA: https://issues.apache.org/jira/browse/YETUS-941

YETUS-941. Wrong URL in the checkstyle report.

---

precommit/src/main/shell/test-patch.sh

Instead of parsing the output targeted at a human, let's parse the output targeted at a robot. Also include the vendor information rather than just the vendor-specific version string.

YETUS-943 Test patch fails to extract version information from a JDK11 jvm

---

precommit/src/main/shell/test-patch.d/maven.sh

JIRA: https://issues.apache.org/jira/browse/YETUS-957

YETUS-957. maven.sh fails to parse maven version

---

asf-site-src/source/documentation/in-progress/precommit-basic.html.md

JIRA: https://issues.apache.org/jira/browse/YETUS-958

YETUS-958. precommit-basic docs contains merge conflict marker

---

asf-site-src/source/documentation/in-progress/precommit-advanced.html.md

JIRA: https://issues.apache.org/jira/browse/YETUS-959

YETUS-959. Dead links in precommit-advanced

---

asf-site-src/data/htaccess.yml
asf-site-src/source/contribute/releases.html.md
asf-site-src/source/downloads.html.md.erb
yetus-dl.sh

JIRA: https://issues.apache.org/jira/browse/YETUS-967

YETUS-967. Switch everything to https://downloads.apache.org

---

.circleci/config.yml
.cirrus.yml
.github/workflows/yetus.yml
.rubocop.yml
.travis.yml
Jenkinsfile
asf-site-src/Dockerfile
asf-site-src/config.rb
asf-site-src/ruby27_fix_uri.rb
pom.xml
precommit/src/main/shell/core.d/00-yetuslib.sh
precommit/src/main/shell/core.d/patchfiles.sh
precommit/src/main/shell/core.d/reaper.sh
precommit/src/main/shell/personality/hbase.sh
precommit/src/main/shell/test-patch-docker/Dockerfile
precommit/src/main/shell/test-patch.d/checkstyle.sh
precommit/src/main/shell/test-patch.d/github.sh
precommit/src/main/shell/test-patch.d/gitlab.sh
precommit/src/main/shell/test-patch.d/jira.sh
precommit/src/main/shell/test-patch.d/spotbugs.sh
precommit/src/main/shell/test-patch.sh
releasedocmaker/pom.xml
shelldocs/pom.xml

This updates everything (I think) with the notable exception of Middleman. Upgrading to Middleman 4.6.8 broke way too much stuff to do as part of this update.

YETUS-982: Upgrade to Ubuntu Focal and update all dependencies/built-ins

---

.circleci/config.yml
.cirrus.yml
.github/workflows/yetus.yml
.gitlab-ci.yml
.semaphore/semaphore-build.sh
.travis.yml
Dockerfile
Jenkinsfile
README.md
asf-site-src/Dockerfile
asf-site-src/source/contribute/releases.html.md
asf-site-src/source/contribute/website.html.md
asf-site-src/source/documentation/in-progress/precommit-advanced.html.md
asf-site-src/source/documentation/in-progress/precommit-basic.html.md
asf-site-src/source/documentation/in-progress/precommit-robots.html.md
asf-site-src/source/documentation/in-progress/precommit-testformats.html.md
asf-site-src/source/downloads.html.md.erb
asf-site-src/source/yetus-docker-image.html.md
precommit/src/main/shell/core.d/01-common.sh
precommit/src/main/shell/personality/yetus.sh
precommit/src/main/shell/test-patch.d/jira.sh
precommit/src/main/shell/test-patch.sh
start-build-env.sh

Note: this is dependent upon #123

YETUS-986.  Switch development branch to 'main'

---

precommit/src/main/shell/test-patch.d/maven.sh

This functionality is only enabled if `--mvn-only-changed-tests=true`

YETUS-21. patch to a unit test should only trigger that unit test

---

precommit/src/main/shell/test-patch.d/github.sh

Woops, left the curl output still going to the screen.

YETUS-994. Add GitHub Status as a report type (addendum)

---

precommit/src/main/shell/test-patch.d/github.sh

JIRA: https://issues.apache.org/jira/browse/YETUS-1007

YETUS-1007. Logging when adding GitHub commit statuses

---

.asf.yaml

JIRA: https://issues.apache.org/jira/browse/YETUS-1008

YETUS-1008. Add .asf.yaml to allow GitHub to JIRA integration

---

.github/workflows/action-test.yml
.github/workflows/yetus.yml
asf-site-src/Dockerfile
asf-site-src/source/documentation/in-progress/precommit/robots/githubactions.html.md
asf-site-src/source/documentation/in-progress/precommit/usage-intro.html.md
precommit/src/main/shell/core.d/01-common.sh
precommit/src/main/shell/test-patch.sh
start-build-env.sh

* use the github action to test the main tree in addition
to the normal testing
* speed up the github action bits in use by caching maven
and fix some related issues with using a pre-built cache
* add documentation about --ignore-unknown-options
* add --report-unknown-options support and docs

YETUS-992. Create and publish a github action (more)

---

asf-site-src/pom.xml
asf-site-src/source/downloads/.gitignore
asf-site-src/source/downloads/index.html.md.erb
releasedocmaker/src/main/python/releasedocmaker/__init__.py

* fix a bug with README generation
* add a --prettyindex to match our middleman config
* add a link to the downloads page
* make sure not to commit the generated page

YETUS-1036. Provide comprehensive changelogs and release notes

---

precommit/src/main/shell/core.d/00-yetuslib.sh
precommit/src/main/shell/test-patch.d/shellcheck.sh
precommit/src/test/resources/arrayfiletest.txt
precommit/src/test/shell/run-bats.sh
precommit/src/test/shell/yetus_abs.bats
precommit/src/test/shell/yetus_array_contains.bats
precommit/src/test/shell/yetus_array_to_comma.bats
precommit/src/test/shell/yetus_del_array_element.bats
precommit/src/test/shell/yetus_file_to_array.bats
precommit/src/test/shell/yetus_find_deepest_directory.bats
precommit/src/test/shell/yetus_relative_dir.bats
precommit/src/test/shell/yetus_sort_and_unique_array.bats
precommit/src/test/shell/yetus_sort_array.bats

Additionally, this change:
* fixes some bugs
* adds shellcheck support for bats files

YETUS-1055. Add test code for yetuslib

---

.codespellignorelines
asf-site-src/config.rb
asf-site-src/source/documentation/in-progress/precommit/plugins/codespell.html.md
precommit/src/main/shell/core.d/change-analysis.sh
precommit/src/main/shell/test-patch-docker/Dockerfile
precommit/src/main/shell/test-patch.d/codespell.sh
website-tester.sh

Preliminary patch because I'm not sure the dev version of codespell used here is quite stable yet. Plus should probably have a way to update the dictionary automatically in the container.  That said, it's be very helpful in our own development. Soooo?

YETUS-1065. Add support for codespell

---

shelldocs/src/main/python/shelldocs.py

* turn replaceb into a bool so that it always has a value
* make the lint actually check the text not what the template table
looks like
* fix the condition where the output file doesn't have a directory

YETUS-1089. replaceable is not consistently handled

---

.asf.yaml

JIRA: https://issues.apache.org/jira/browse/YETUS-1118

YETUS-1118. Add .asf.yaml to asf-site branch to deploy website

---

asf-site-src/config.rb
asf-site-src/source/downloads/index.html.md.erb

Kudos to @ndimiduk's questions in #259 for pushing me to realize there was extra work happening here.

YETUS-1163. Remove changelog data from config.rb

---

asf-site-src/source/contribute/releases.html.md
asf-site-src/source/mailinglists.html.md
pom.xml

I'm going to do this one in two parts.  Here's the first one.

YETUS-1181. post-0.14.0 release doc updates (part 1)

---

.buildkite/pipeline.yml
.circleci/config.yml
.cirrus.yml
.github/workflows/yetus.yml
.gitlab-ci.yml
Jenkinsfile
precommit/src/main/shell/core.d/00-yetuslib.sh
precommit/src/main/shell/plugins.d/csvout.sh
precommit/src/main/shell/plugins.d/htmlout.sh
precommit/src/test/shell/yetus_trim.bats

This is a somewhat trivial implementation of a csv-style report.  I have no idea if it will work with what @busbey had in mind though...

YETUS-277. full report in csv format
